### PR TITLE
Update for modern Node versions

### LINKED ISSUE #50: Build failing on Node 15
It looks like node-gyp changes are needed for building in Node 15.

Detected in this failing Comunica build: https://travis-ci.org/github/comunica/comunica-actor-init-sparql-hdt/jobs/738833991

### PR DESCRIPTION
**Pull request by rubensworks**
This updates nan so we're compatible with recent Node versions.

This also replaces the travis file with a GH CI file.

Closes #50

This is a requirement for updating HDT support in Comunica.

### CODE REVIEW

**Comment by RubenVerborgh** [comment]
Thanks @rubensworks, glad it's still working!

**Comment by rubensworks** [comment]
Would it be possible to publish a new release to npm?
The changes to `binding.gyp` are needed to compile.

**Comment by RubenVerborgh** [comment]
Released as v3.0.3

image

**Comment by rubensworks** [comment]
Thanks :-)

**Pull request merged**
