### PR TITLE
Preliminary fix for #30: Searches of limit 0 now return 0 results

### LINKED ISSUE #30: A Limit of 0 returns all results
In C++, the negative of 0 is 1. This causes a problem with Limit set to 0 (no triples should ever be returned) on https://github.com/RubenVerborgh/HDT-Node/blob/master/lib/HdtDocument.cc#L165, where instead, the complete iterator is added to the vector. This causes the `countTriples()` method, which sets `limit = 0`, to be extremely inefficient. 

The main problem here is that 'no limit' is also supplied as 0. A possible solution is to encode 'no limit' as -1 or infinity.

### PR DESCRIPTION
**Pull request by mielvds**
Fixes #30 by setting limits of 0 to 1 in JS and returning an empty array. 
This is not the best/desired fix, but it will do for now. 

In a future version, find a way to communicate zero limits to C++, or rather, communicate unset limits to C++ and not iterate over the results at all when the limit is 0.

### CODE REVIEW

**Comment by RubenVerborgh** [comment]
Can you also check, in the method that returns triples, whether it bails out if the limit is 0? We can even bail out in the JavaScript code.

**Comment by mielvds** [comment]
Not sure I follow. This PR doesn't change the semantics of te method AFAIK?

**Comment by RubenVerborgh** [comment]
Sorry, trying again :-)

1. You've discovered a bug exists with the methods that _counts_ triples because we passed a limit of 0.
2. I wonder, would a similar bug exist with the method that _gets_ triples if we pass a limit of 0?

If 2 is the case, then we might want to patch that method such that it returns early when the limit is 0. (However, contrary to what I said above, when can not do that in the JavaScript code: even is the limit is 0, we still need to return a count.)

**Comment by mielvds** [comment]
Yes b) is what I've been saying al along :) The problem is searching/getting with a limit set to 0, which is what count does. And we can't do that in the current C code either I'm afraid as you can't distinguish limit 0 from NULL. That's why I said: "In a future version, find a way to communicate zero limits to C++, or rather, communicate unset limits to C++ and not iterate over the results at all when the limit is 0."

**Comment by RubenVerborgh** [comment]
Well, your point is about the hdt-cpp internals not distinguishing between “none” and “0“. Agreed that it should be fixed there, and this PR is a workaround to fix count.

My point is rather that we should fix the `searchTriples` method of the hdt-node library to account for that problem, in addition to fixing count.

**Comment by mielvds** [comment]
Well hdt-cpp actually doesn't know the concept of limit. It returns an iterator which you deplete until the limit is reached. The count method is attached to the iterator.

However, the `SearchTriplesWorker` in `HDTDocument.cc` could indeed be fixed, for example by:
- allowing -1 as limit to indicate unlimited
- overloading the constructor that omits the limit parameter (not sure how that works in nan)
- adding an unlimited parameter to the signature

**Comment by RubenVerborgh** [comment]
Okay, thanks! Will reviews this PR soon.

**Comment by RubenVerborgh** [comment]
Thanks, created alternative fix b5e3fc1e5cebe86a34b6d2a0f6f4b506bcfe9e59 (HDT files with larger sizes will create trouble in JavaScript-land anyway).

**Pull request closed without merging**
